-- Sample Asset Data for Preventive Maintenance System
-- Insert this data after running the main migration

-- Insert sample maintenance assets with camelCase column names
INSERT INTO public.maintenance_assets (
    "assetName",
    "assetCode",
    "categoryId",
    "locationBuilding",
    "locationFloor",
    "locationRoom",
    "makeModel",
    "serialNumber",
    "purchaseDate",
    "warrantyExpiry",
    "installationDate",
    specifications,
    status,
    criticality,
    notes,
    "createdAt",
    "updatedAt"
) VALUES
-- HVAC Systems (Category ID: 1)
(
    'Central Air Conditioning Unit A1',
    'HVAC-001',
    1,
    'Block A',
    'Rooftop',
    'Mechanical Room 1',
    'Carrier 30XA1002',
    'CAR-2023-001',
    '2023-01-15',
    '2028-01-15',
    '2023-02-01',
    '{"capacity": "100 tons", "refrigerant": "R-410A", "voltage": "480V", "phases": 3}',
    'active',
    'critical',
    'Main cooling system for Block A. Requires monthly filter changes.',
    NOW(),
    NOW()
),
(
    'Chiller Unit B1',
    'HVAC-002',
    1,
    'Block B',
    'Basement',
    'Chiller Room',
    'Trane CVHF1000',
    'TRA-2022-045',
    '2022-06-10',
    '2027-06-10',
    '2022-07-01',
    '{"capacity": "500 tons", "coolant": "Water", "efficiency": "0.58 kW/ton"}',
    'active',
    'critical',
    'Primary chiller for Block B. Critical for building operations.',
    NOW(),
    NOW()
),
(
    'AHU - Lobby Level',
    'HVAC-003',
    1,
    'Main Building',
    'Ground Floor',
    'AHU Room 1',
    'York YMC2 Series',
    'YRK-2023-012',
    '2023-03-20',
    '2028-03-20',
    '2023-04-05',
    '{"airflow": "15000 CFM", "motor": "15 HP", "filtration": "MERV 13"}',
    'active',
    'high',
    'Air handling unit for lobby and common areas.',
    NOW(),
    NOW()
),

-- Electrical Systems (Category ID: 2)
(
    'Main Electrical Panel A',
    'ELEC-001',
    2,
    'Block A',
    'Basement',
    'Electrical Room 1',
    'Square D PowerPact',
    'SQD-2023-001',
    '2023-01-10',
    '2033-01-10',
    '2023-01-25',
    '{"voltage": "480V", "amperage": "2000A", "phases": 3, "breakers": 42}',
    'active',
    'critical',
    'Main distribution panel for Block A. Critical infrastructure.',
    NOW(),
    NOW()
),
(
    'Emergency Generator',
    'ELEC-002',
    2,
    'Main Building',
    'Ground Floor',
    'Generator Room',
    'Caterpillar C32',
    'CAT-2022-089',
    '2022-08-15',
    '2027-08-15',
    '2022-09-01',
    '{"power": "1000 kW", "fuel": "Diesel", "runtime": "24 hours", "voltage": "480V"}',
    'active',
    'critical',
    'Backup power for essential systems during outages.',
    NOW(),
    NOW()
),
(
    'UPS System - Data Center',
    'ELEC-003',
    2,
    'Block C',
    '2nd Floor',
    'Server Room',
    'APC Symmetra PX',
    'APC-2023-007',
    '2023-05-12',
    '2028-05-12',
    '2023-05-20',
    '{"capacity": "100 kVA", "runtime": "30 minutes", "batteries": 40}',
    'active',
    'high',
    'Uninterruptible power supply for critical IT equipment.',
    NOW(),
    NOW()
),

-- Plumbing Systems (Category ID: 3)
(
    'Main Water Pump P1',
    'PLUMB-001',
    3,
    'Main Building',
    'Basement',
    'Pump Room',
    'Grundfos CR 64-2',
    'GRU-2023-001',
    '2023-02-01',
    '2028-02-01',
    '2023-02-15',
    '{"flow_rate": "500 GPM", "head": "200 ft", "motor": "75 HP", "efficiency": "85%"}',
    'active',
    'critical',
    'Primary water supply pump for entire building complex.',
    NOW(),
    NOW()
),
(
    'Hot Water Heater - Block A',
    'PLUMB-002',
    3,
    'Block A',
    'Basement',
    'Utility Room',
    'Rheem Professional',
    'RHE-2022-034',
    '2022-11-20',
    '2032-11-20',
    '2022-12-01',
    '{"capacity": "200 gallons", "input": "500,000 BTU", "efficiency": "95%"}',
    'active',
    'medium',
    'Hot water supply for Block A residential units.',
    NOW(),
    NOW()
),
(
    'Sewage Ejector Pump',
    'PLUMB-003',
    3,
    'Block B',
    'Sub-basement',
    'Sewage Room',
    'Liberty P382LE51',
    'LIB-2023-009',
    '2023-04-10',
    '2028-04-10',
    '2023-04-18',
    '{"flow_rate": "165 GPM", "head": "51 ft", "solids": "2 inch", "motor": "1 HP"}',
    'active',
    'high',
    'Sewage pump for basement level facilities.',
    NOW(),
    NOW()
),

-- Elevator Systems (Category ID: 4)
(
    'Passenger Elevator A1',
    'ELEV-001',
    4,
    'Block A',
    'All Floors',
    'Elevator Shaft 1',
    'Otis Gen2 Premier',
    'OTIS-2023-001',
    '2023-01-05',
    '2028-01-05',
    '2023-02-20',
    '{"capacity": "3500 lbs", "speed": "500 FPM", "floors": 20, "doors": "Center Opening"}',
    'active',
    'critical',
    'Main passenger elevator for Block A. High traffic usage.',
    NOW(),
    NOW()
),
(
    'Service Elevator B1',
    'ELEV-002',
    4,
    'Block B',
    'All Floors',
    'Service Shaft',
    'Schindler 3300',
    'SCH-2022-078',
    '2022-09-15',
    '2027-09-15',
    '2022-10-01',
    '{"capacity": "5000 lbs", "speed": "350 FPM", "floors": 15, "type": "Freight"}',
    'active',
    'high',
    'Service elevator for moving equipment and supplies.',
    NOW(),
    NOW()
),

-- Fire Safety Systems (Category ID: 5)
(
    'Fire Alarm Control Panel',
    'FIRE-001',
    5,
    'Main Building',
    'Ground Floor',
    'Security Office',
    'Honeywell NOTIFIER NFS2-3030',
    'HON-2023-003',
    '2023-01-20',
    '2028-01-20',
    '2023-02-10',
    '{"zones": 99, "devices": 636, "network": "NFNET2", "backup": "24V Battery"}',
    'active',
    'critical',
    'Central fire alarm system for entire complex.',
    NOW(),
    NOW()
),
(
    'Fire Sprinkler Pump',
    'FIRE-002',
    5,
    'Main Building',
    'Basement',
    'Fire Pump Room',
    'Peerless Fire Pumps 4AE11',
    'PEER-2022-056',
    '2022-07-25',
    '2027-07-25',
    '2022-08-10',
    '{"flow": "1500 GPM", "pressure": "125 PSI", "motor": "200 HP", "fuel": "Diesel"}',
    'active',
    'critical',
    'Fire suppression system pump. Weekly testing required.',
    NOW(),
    NOW()
),

-- Security Systems (Category ID: 6)
(
    'Main Security Server',
    'SEC-001',
    6,
    'Main Building',
    'Ground Floor',
    'Security Control Room',
    'Genetec Security Center',
    'GEN-2023-001',
    '2023-03-01',
    '2028-03-01',
    '2023-03-15',
    '{"cameras": 128, "storage": "100 TB", "retention": "90 days", "users": 50}',
    'active',
    'high',
    'Central security management system with video surveillance.',
    NOW(),
    NOW()
),
(
    'Access Control System',
    'SEC-002',
    6,
    'All Buildings',
    'All Floors',
    'Various Locations',
    'HID VertX V1000',
    'HID-2023-012',
    '2023-02-15',
    '2028-02-15',
    '2023-03-01',
    '{"doors": 200, "cards": 5000, "readers": 400, "network": "TCP/IP"}',
    'active',
    'high',
    'Building access control system for all entry points.',
    NOW(),
    NOW()
),

-- Lighting Systems (Category ID: 7)
(
    'LED Lighting Controller - Lobby',
    'LIGHT-001',
    7,
    'Main Building',
    'Ground Floor',
    'Electrical Closet 1',
    'Lutron Quantum',
    'LUT-2023-005',
    '2023-04-01',
    '2028-04-01',
    '2023-04-10',
    '{"zones": 24, "dimmers": 48, "sensors": 16, "protocol": "sACN"}',
    'active',
    'medium',
    'Automated lighting control for main lobby area.',
    NOW(),
    NOW()
),
(
    'Emergency Lighting System',
    'LIGHT-002',
    7,
    'All Buildings',
    'All Floors',
    'Various Locations',
    'Cooper Lighting Sure-Lites',
    'COOP-2022-089',
    '2022-10-15',
    '2027-10-15',
    '2022-11-01',
    '{"units": 150, "battery_life": "90 minutes", "test_cycle": "Monthly"}',
    'active',
    'high',
    'Emergency egress lighting throughout all buildings.',
    NOW(),
    NOW()
),

-- General Maintenance Equipment (Category ID: 10)
(
    'Industrial Vacuum System',
    'GEN-001',
    10,
    'Main Building',
    'Basement',
    'Maintenance Shop',
    'Nilfisk VHW420',
    'NIL-2023-002',
    '2023-05-01',
    '2026-05-01',
    '2023-05-05',
    '{"power": "5.5 kW", "capacity": "100L", "filtration": "HEPA", "hose_length": "10m"}',
    'active',
    'medium',
    'Heavy-duty vacuum for maintenance operations.',
    NOW(),
    NOW()
),
(
    'Floor Scrubber Machine',
    'GEN-002',
    10,
    'Main Building',
    'Ground Floor',
    'Janitor Closet',
    'Tennant T7AMR',
    'TEN-2023-008',
    '2023-06-15',
    '2026-06-15',
    '2023-06-20',
    '{"cleaning_width": "28 inches", "solution_tank": "17 gallons", "battery": "Lithium"}',
    'active',
    'medium',
    'Autonomous floor cleaning machine for common areas.',
    NOW(),
    NOW()
),

-- Retired/Inactive Assets for Testing
(
    'Old Boiler System',
    'HVAC-RETIRED-001',
    1,
    'Block C',
    'Basement',
    'Old Boiler Room',
    'Burnham V8H-3',
    'BUR-2015-001',
    '2015-03-10',
    '2020-03-10',
    '2015-04-01',
    '{"capacity": "2 million BTU", "fuel": "Natural Gas", "efficiency": "85%"}',
    'retired',
    'low',
    'Replaced by new HVAC system in 2023. Kept for parts.',
    NOW(),
    NOW()
),
(
    'Maintenance Equipment - Under Repair',
    'GEN-003',
    10,
    'Main Building',
    'Basement',
    'Maintenance Shop',
    'DeWalt Air Compressor',
    'DEW-2022-015',
    '2022-05-20',
    '2025-05-20',
    '2022-05-25',
    '{"pressure": "175 PSI", "tank": "80 gallons", "motor": "5 HP"}',
    'maintenance',
    'medium',
    'Currently under repair. Motor replacement needed.',
    NOW(),
    NOW()
);

-- Update the sequence to continue from the inserted data
SELECT setval('maintenance_assets_id_seq', (SELECT MAX(id) FROM maintenance_assets));

-- Verify the inserted data
-- SELECT COUNT(*) as total_assets FROM maintenance_assets;
-- SELECT status, COUNT(*) as count FROM maintenance_assets GROUP BY status;
-- SELECT ac.name as category, COUNT(ma.id) as asset_count 
-- FROM asset_categories ac 
-- LEFT JOIN maintenance_assets ma ON ac.id = ma.categoryId 
-- GROUP BY ac.id, ac.name 
-- ORDER BY ac.name;
